# Generated by Django 5.2.15 on 2026-06-24 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('desired_position', models.CharField(blank=True, max_length=255, verbose_name='Желаемая должность')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки и технологии')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('projects', models.TextField(blank=True, verbose_name='Проекты и реальные кейсы')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('strengths', models.TextField(blank=True, verbose_name='Сильные стороны')),
                ('ai_instructions', models.TextField(blank=True, verbose_name='Дополнительные инструкции для нейронки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('company_url', models.URLField(blank=True, verbose_name='Ссылка на сайт компании')),
                ('vacancy_url', models.URLField(blank=True, verbose_name='Ссылка на вакансию')),
                ('description', models.TextField(verbose_name='Описание вакансии с hh.ru')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки пользователя')),
                ('generated_resume', models.TextField(blank=True, verbose_name='Сгенерированное резюме')),
                ('generated_resume_latex', models.TextField(blank=True, verbose_name='LaTeX резюме')),
                ('generated_cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('generated_interview_tips', models.TextField(blank=True, verbose_name='Советы для собеседования')),
                ('fit_assessment', models.TextField(blank=True, verbose_name='Оценка соответствия')),
                ('resume_pdf', models.FileField(blank=True, upload_to='resumes/', verbose_name='PDF резюме')),
                ('resume_tex', models.FileField(blank=True, upload_to='resumes/', verbose_name='LaTeX файл')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Сгенерировано')),
                ('generation_log', models.TextField(blank=True, verbose_name='Лог генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Pi агент')], max_length=16)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='applications.vacancy')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
    ]
