# Generated by Django 5.2.15 on 2026-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_profile_user_vacancy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='generation_error',
            field=models.TextField(blank=True, verbose_name='Ошибка генерации'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='generation_status',
            field=models.CharField(choices=[('idle', 'Нужно сгенерировать'), ('running', 'Идёт генерация'), ('success', 'Успешно'), ('error', 'Ошибка')], default='idle', max_length=16, verbose_name='Статус генерации'),
        ),
    ]
